# Env definition file for creating environment via conda

name: projects-env
channels:
 - conda-forge
dependencies:
 # core / build
 - python >= 3.11
 - cf-units
 - iris >= 3.10
 - xarray
 - jinja2
 - numpy
 - pandas
 - humanize
 - yaml
 - pip
 - setuptools>=68
 - setuptools_scm>=8.0
 - calver  # CalVer package versioning

 # analysis / extended capabilities
 #- scikit-sparse
 #- h5py
 #- scipy
 #- pandera
 #- pandera-io
 #- ipython
 #- geopandas
 #- pipreqs

 # visualisation
 #- holoviews
 #- geoviews

 # code style and pre-commit
 - pre-commit
 - black
 - codespell
 - isort
 - flake8
 - blacken-docs
 - pycln

 # testing
 - coverage
 - pytest
 - pytest-cov
 - compliance-checker

 # documentation
 - sphinx
 - sphinx_rtd_theme
 - sphinx-argparse
 - sphinx-gallery
 - sphinxcontrib-mermaid
 - myst-parser
 - numpydoc

 # security fixes - KEEP UNDER REVIEW
 - libwebp-base >= 1.3.2
 - libwebp >= 1.3.2